version: '2'
services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: npm run server
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    links:
      - mongodb
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    command: npm start
    restart: always
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    links:
      - server
    ports:
      - '3000:3000'
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    links:
      - mongodb
