export const boardConstants = {
  GET_ALL_BOARDS_REQUEST: 'GET_ALL_BOARDS_REQUEST',
  GET_ALL_BOARDS_SUCCESS: 'GET_ALL_BOARDS_SUCCESS',
  GET_ALL_BOARDS_FAILURE: 'GET_ALL_BOARDS_FAILURE',

  GET_BOARD_REQUEST: 'GET_BOARD_REQUEST',
  GET_BOARD_SUCCESS: 'GET_BOARD_SUCCESS',
  GET_BOARD_FAILURE: 'GET_BOARD_FAILURE'
};
