export const taskConstants = {
  ADD_TASK: 'ADD_TASK',
  ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
  ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',

  DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_FAILURE: 'DELETE_TASK_FAILURE',

  EDIT_TASK_REQUEST: 'EDIT_TASK_REQUEST',
  EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCESS',
  EDIT_TASK_FAILURE: 'EDIT_TASK_FAILURE',

  ADD_TASKLIST: 'ADD_TASKLIST',
  INIT_TASKLIST: 'INIT_TASKLIST',

  EDIT_TASKLIST_REQUEST: 'EDIT_TASKLIST_REQUEST',
  EDIT_TASKLIST_SUCCESS: 'EDIT_TASKLIST_SUCCESS',
  EDIT_TASKLIST_FAILURE: 'EDIT_TASKLIST_FAILURE'
};
